<?php

namespace App\Form\Security\Authentication\FormExtension\Company;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanySectorType extends AbstractType
{


    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'choices' => $this->sectors

        ]);
    }

    public function getParent(): string
    {
        return ChoiceType::class;
    }


    /**
     * @var array|string[]
     */
    private array $sectors = [

        'peinture' => 'peinture',
        'echafaudage' => 'echafaudage',
        'plomberie' => 'plomberie',
        'plaquiste plâtrier' => 'plaquiste plâtrier',
        'autre' => 'autre',


    ];
}