monolog:
    channels:
        - "oauth"
    handlers:
        oauth:
            level: info
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/security/oauth/oauth.%kernel.environment%.log"
        security:
            level: info
            type: rotating_file
            max_files: 15
            channels:
                - "security"

            path: "%kernel.logs_dir%/security/security.%kernel.environment%.log"
        security_debug:
            level: DEBUG
            
            #max_level: DEBUG
            #min_level: DEBUG
            type: rotating_file
            max_files: 10
            channels: ["security"]
            path: "%kernel.logs_dir%/security/security_debug.%kernel.environment%.log"



        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels:
                - "!event"
                - "!security"
                - "!google_oauth"
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
