<?php

namespace App\Form\FormExtension\Company;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanySectorType extends AbstractType
{


    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'choices' => ['secteur d\'activité' => $this->sectors]

        ]);
    }

    public function getParent(): string
    {
        return ChoiceType::class;
    }


    /**
     * @var array|string[]
     */
    private array $sectors = [

        'carrelage' => 'carrelage',
        'couvreur' =>  'couvreur',
        'décorateur' => 'décorateur',
        'echafaudage' => 'echafaudage',
        'élagage' => 'élagage',
        'électricité' =>  'électricité',
        'isolation' => 'isolation',
        'maçonnerie' => 'maçonnerie',
        'menuiserie' => 'menuiserie',
        'paysagiste' => 'paysagiste',
        'peinture' => 'peinture',
        'plaquiste plâtrier' => 'plaquiste plâtrier',
        'plomberie' => 'plomberie',
        'autre' => 'autre',


    ];
}